- name: install and start mysql
  hosts: test
  become: yes

  tasks:
  - name: install 
    ansible.builtin.package:
      name: mysql
      state: present

  - name: start mysql
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes

